### ISSUE TITLE
Create lookup table for charge eligibility

### ISSUE THREAD

**Issue by wdcrumpler-kcdd** [codeforkansascity/KS-CMR#8]
**Goal**: Create a list of crimes by statute number that can be used by the app to look up the statute indicated by the user, compare with other information (like time since they completed their sentence) and return an assessment of whether the person is eligible for expungement.

**Key Resources**:
- [Google Sheet](https://docs.google.com/spreadsheets/d/1GUCQHuSA4-aFXSOOXaxK436yqXH3zsCT4wOb5_MPHLw/edit?usp=sharing) that contains an initial coding of the eligibility requirements for different crime types
- [Full list (Download)](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjh96KSjIr0AhXaaM0KHYwpACEQFnoECAsQAQ&url=https%3A%2F%2Fwww.sentencing.ks.gov%2Fdocs%2Fdefault-source%2F2016-DRM%2F2016-felony-misdemeanor-criminal-code-crime-listing.xls%3Fsfvrsn%3D6a24fc3f_4&usg=AOvVaw0uHF9iRUOySYeL3Ulc_PSR) of KS criminal statutes 

Tasks:
- [ ] Determine how to allow the client to select their charge with specificity (can include multiple approaches that can be A/B tested)
- [ ] Determine how to account for the fact that in previous years, the eligibility of certain crimes may have changed. Simple option: if not eligible under current statutes, tell them to consult with an attorney. Complicated option: get old charge codes and eligibility details and build in a lookup system that triggers depending on the date of the crime.
- [ ] In spreadsheet, build a function that evaluates each crime's information to evaluate how many years must have elapsed before eligibility

**Comment by wdcrumpler-kcdd** [comment]
**Current Status**
- Based on the KS Expungement Statute ([K.S.A. 21-6614](https://www.ksrevisor.org/statutes/chapters/ch21/021_066_0014.html)) and [guidance from KLS](https://www.kansaslegalservices.org/sites/kansaslegalservices.org/files/Chart%20of%20eligibilty%20for%20Expungement_0.pdf), we have an [initial coding](https://docs.google.com/spreadsheets/d/1GUCQHuSA4-aFXSOOXaxK436yqXH3zsCT4wOb5_MPHLw/edit?usp=sharing) of the types of crimes that are expungeable and what the conditions on expungeability are.
- We have found a full list (Download) of KS criminal statutes

**To-Do**
- [ ] Use the two spreadsheets linked above to create a combined spreadsheet where each KS statute is listed along with its eligibility conditions

**Comment by HowSimple** [comment]
I added a lookup table in the "Lookup Charge Eligibility" page of this existing spreadsheet: [https://docs.google.com/spreadsheets/d/1GUCQHuSA4-aFXSOOXaxK436yqXH3zsCT4wOb5_MPHLw/edit#gid=2023437888](https://docs.google.com/spreadsheets/d/1GUCQHuSA4-aFXSOOXaxK436yqXH3zsCT4wOb5_MPHLw/edit#gid=2023437888)
It uses the "Abbreviated Jotform Charge List" to look up each charge, and then shows when that charge is eligible to be expunged based on the date it was completed, and the type of charge (attempt, conspiracy, etc). Even though the years seem similar for each type of charge, it does still
Let me know if there is more info necessary to be entered here.
I'll also work on a basic API for the prototype application to be able to look up charge eligibility like this.
